version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "04:00"
    timezone: Europe/Berlin
  ignore:
  - dependency-name: intl-messageformat
    versions:
    - 9.4.3
    - 9.4.6
    - 9.4.7
    - 9.4.9
    - 9.5.2
    - 9.5.3
    - 9.6.3
    - 9.6.6
    - 9.6.7
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.2
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.3
    - 2.44.0
    - 2.45.1
  - dependency-name: "@formatjs/intl-pluralrules"
    versions:
    - 4.0.11
    - 4.0.12
    - 4.0.13
    - 4.0.14
    - 4.0.5
    - 4.0.6
    - 4.0.8
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.1
    - 7.13.10
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.0
    - 7.13.10
    - 7.13.9
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
    - 7.13.0
